# Generated by Django 5.2.1 on 2025-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('servicio', models.CharField(max_length=100)),
                ('requiere', models.BooleanField(default=False)),
                ('tecnologia_cliente', models.CharField(blank=True, max_length=100)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
